trigger:
- main

pool:
  vmImage: 'windows-latest'

jobs:
- job: RestartJob
  displayName: 'Execute Restart Command'
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # PowerShell script to restart the machine
        Restart-Computer -ComputerName "localhost" -Force
    displayName: 'Run Restart Command'
