trigger:
- main

pool:
  name: 'Azure Pipelines'  # Replace 'Default' with the name of your self-hosted agent pool

jobs:
- job: RestartJob
  displayName: 'Execute Restart Command on Self-Hosted Agent'
  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        # PowerShell script to restart the machine
        Restart-Computer -Force
    displayName: 'Run Restart Command'
